name: run-tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - "*"

permissions:
  actions: write

jobs:
  checks:
    name: checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - name: dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: pytest
        run: pytest